export const ActionTypes = {
	UPDATE_PAGE: "UPDATE_PAGE",
	UPDATE_ROUTE: "UPDATE_ROUTE",
	START_MINING: "START_MINING",
	STOP_MINING: "STOP_MINING",
	UPDATE_CONFIG: "UPDATE_CONFIG",
	UPDATE_LOGS: "UPDATE_LOGS",
};